### ISSUE TITLE
Error showing in commands

### ISSUE THREAD

**Issue by pushpendra07** [Ethan3600/EthanYehuda_CronjobManager#128] opened 2019-07-19 11:08 UTC
**Describe the bug**
Showing error in Magento CLI commands
**To Reproduce**
1. Installed plugin by composer and run Magento2 upgrade command

**Expected behavior**
Commands should run without error
**Screenshots**
![AwesomeScreenshot-Screenshot-from-2019-07-19-16-32-04-2019-07-19-16-07-76](https://user-images.githubusercontent.com/8010768/61531093-7db42700-aa43-11e9-8938-2a12e83e0687.png)

**Environment (please complete the following information):**
 - OS: Centos
 - Browser: chrome
 - Cron Job Manager Version [1.8.0]
 - Magento Version [2.2.4]
 - PHP Version [7.1.0]

**Comment by Ethan3600** [comment] 2019-07-20 19:48
@pushpendra07 Thanks for submitting this issue! I can't reproduce this on the latest version of the Cron Job Manager. Can you try upgrading to the latest version (v1.9.0).

**Comment by simonrl** [comment] 2019-07-23 08:49
I can reproduce this on PHP 7.1, Magento 2.2.6, Cronjobmanager 1.9.0

I had a short look at the code, and it actually seems ok to me... so no idea where this error comes from.

To reproduce:
1. composer u --no-dev
2. php bin/magento setup:upgrade
-> does not work, runs into mentioned error
3. rm -r generated/* 
4. php bin/magento setup:upgrade
-> still the same error.

All running in developer mode.

**Comment by pushpendra07** [comment] 2019-07-26 11:57
@Ethan3600, It's showing same error for latest version

**Comment by Ethan3600** [comment] 2019-07-27 18:15
Ok, I was on Magento version 2.3.1. That's why I didn't see it. Sorry for the mistake.

Good News: I was able to reproduce on Magento version 2.2.6

Bad News: This seems to be a bug in _some versions_ of Magento 2.2.x: https://github.com/magento/magento2/issues/6106

There were more issues opened up for this, and I can't tell which release the fix was merged into.

Anyway, the problem was this:

The CJM's code had a method signature with a return type-hint like this: 
`public function execute(int $scheduleId): bool`

But, the generated code was spitting out something like this: 
`public function execute(int $scheduleId)` 

Which causes php to throw an error because the signature doesn't match.

I can confirm that this is fixed in the latest 2.2.x release (at the time of writing, it's v2.2.9).

I'm going to close this due to it being a Magento bug. 

Feel free to comment to discuss further!

**Closed as completed by Ethan3600** 2019-07-27 18:15 UTC
Labels: Magento Bug
