### ISSUE TITLE
Exception #0 (Exception): Notice: Undefined index: name

### ISSUE THREAD

**Issue by refueledinc** [Ethan3600/EthanYehuda_CronjobManager#38] opened 2018-04-16 18:15 UTC
On magento 2.2.3 when clicking on `Job Configuration` or `Select > edit` I get the below error:
```
1 exception(s):
Exception #0 (Exception): Notice: Undefined index: name in [store_path]/vendor/ethanyehuda/magento2-cronjobmanager/Model/Schedule/Source/Schedule.php on line 32
```

**Comment by refueledinc** [comment] 2018-04-16 18:48
It seems the issue is somehow related to my disabling of one of magento's core modules:
```
bin/magento module:disable Dotdigitalgroup_Email Magento_Dhl Magento_Braintree Magento_GoogleAdwords Magento_NewRelicReporting Magento_ReleaseNotification Magento_Signifyd Magento_SampleData Shopial_Facebook Temando_Shipping Magento_WishlistAnalytics Magento_GoogleOptimizer Magento_GoogleAnalytics Magento_Version Magento_Multishipping Magento_Weee Magento_Analytics
```

**Comment by refueledinc** [comment] 2018-04-16 18:53
It appears related to the `Magento_Analytics` module being disabled

**Comment by Ethan3600** [comment] 2018-04-17 00:54
Hi @refueledinc, thank you for reporting the issue and using the CJM.

I think I figured it out.

Magento_Analytics doesn't have cron expressions set by default:

![image](https://user-images.githubusercontent.com/6549623/38842310-3e86c7a4-41b7-11e8-81eb-2332e030b7db.png)

So when we grab the configuration information, php gets mad because we're assuming the index (in this case `schedule`) exists [here](https://github.com/Ethan3600/magento2-CronjobManager/blob/1.x/Ui/DataProvider/ConfigDataProvider.php#L66)

I think this warrants some more safe guards against empty values in all data providers.

I'm going to make a new patch release asap.

**Comment by Ethan3600** [comment] 2018-04-17 02:31
I think my original assessment was wrong, but consequently, I did find another (unrelated) undefined index exception... 

Albeit, I am having difficulty reproducing the issue on v1.3.2. Probably should've asked this before I started debugging, but what version of the CJM are you using? What mode (i.e. production, default, developer) are you running Magento in?

Regardless, I should probably add some "check" to make sure the **name** index isn't empty before calling it [around here](https://github.com/Ethan3600/magento2-CronjobManager/blob/1.x/Model/Schedule/Source/Schedule.php#L32L33). Ultimately I think that's the issue so I'll release a new version anyway.

Lastly out of curiosity, does flushing cache fix the issue? Since Magento merges all config (xmI) files and caches the result, I wonder if the final merged config XML is outdated at the time of calling `$this->cronConfig->getJobs()`? Would you mind checking to see if that fixes the issue?

**Comment by refueledinc** [comment] 2018-04-17 10:01
Hello thanks for the quick support. I'm using magento 2.2.3 in developer mode and version 1.3.2 of your extension. Although I just updated to 1.3.3 now. Cache clean/flush does not help.

**Comment by refueledinc** [comment] 2018-04-17 10:05
By the way, with quick testing, it seems version 1.3.3 fixes this issue.

**Comment by Ethan3600** [comment] 2018-04-17 12:06
Cool! I'll close this out then.

If you have any other issues, please open another ticket.

**Closed as completed by Ethan3600** 2018-04-17 12:06 UTC
Labels: High Bug
