### ISSUE TITLE
how to mass delete the cron job about the status is success?

### ISSUE THREAD

**Issue by benyang2015** [Ethan3600/EthanYehuda_CronjobManager#45] opened 2018-04-21 00:33 UTC

**Comment by Ethan3600** [comment] 2018-04-21 02:43
Hi @benyang2015 this is a duplicate of this issue: https://github.com/Ethan3600/magento2-CronjobManager/issues/21

Mass actions are in the pipeline, but I haven't started development on it yet. I'm willing to accelerate the process by placing it in the **priority to do** list. Please see [the pipeline](https://github.com/Ethan3600/magento2-CronjobManager/projects/1) for development details.

I'm going to close this issue because it's redundant. If you have any other concerns relating to mass actions, please place them here: https://github.com/Ethan3600/magento2-CronjobManager/issues/21

Thank you for using the CJM!

**Closed as completed by Ethan3600** 2018-04-21 02:43 UTC
Labels: duplicate
